name: 🐞 Bug Report
description: Report an error in this repository
title: "Fix: "
labels: [ "bug" ]
assignees:
  - freearhey

body:
  - type: markdown
    attributes:
      value: |
       Please describe the error in as much detail as possible so that we can fix it quickly

  - type: textarea
    id: bug
    attributes:
      label: Describe your issue
    validations:
      required: true
