name: 🛠 Broken Stream
description: Report a broken stream
title: "Fix: "
labels: [ "broken stream" ]
body:
  - type: markdown
    attributes:
      value: |
       Please fill out the issue template as much as you can so we could efficiently process your request
       **IMPORTANT**: An issue may contain a request for only one channel, otherwise it will be closed
