blank_issues_enabled: true
contact_links:
  - name: Channel Request
    url: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=channel+request&template=channel-request.md&title=Add%3A+xxx
    about: Request to add a channel to the playlist
  - name: Feature Request
    url: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=feature+request&template=feature-request.md&title=Suggestion%3A+xxx
    about: Suggest an idea for this project
  - name: Broken Stream
    url: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=broken+stream&template=broken-stream.md&title=Fix%3A+xxx
    about: Request to replace a broken stream
  - name: Remove Channel
    url: https://github.com/iptv-org/iptv/issues/new?assignees=&labels=DMCA&template=remove-channel.md&title=Remove%3A+xxx
    about: Request to remove a channel from the playlist
