name: auto-approve
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: github.head_ref == 'create-pull-request/patch'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
