name: auto-approve
on: 
  pull_request:
    branches:
      - create-pull-request/patch-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"