name: auto-update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Create Branch
        run: |
          git fetch --prune --unshallow
          git checkout bot/auto-update || git checkout -b bot/auto-update
      - name: Install Dependencies
        run: npm install
      - name: Remove Duplicates
        run: node scripts/remove-duplicates.js
      - name: Commit Changes
        run: |
          git add channels/*
          git diff-index --quiet HEAD || git commit -m "[Bot] Remove duplicates"
      - name: Format Playlists
        run: node scripts/format.js
      - name: Commit Changes
        run: |
          git add channels/*
          git diff-index --quiet HEAD || git commit -m "[Bot] Format playlists"
      - name: Generate Playlists
        run: node scripts/generate.js
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: .gh-pages
      - name: Update README.md
        run: node scripts/update-readme.js
      - name: Commit Changes
        run: |
          git add README.md
          git diff-index --quiet HEAD || git commit -m "[Bot] Update README.md"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[Bot] Update Playlists'
          body: |
            This pull request is created automatically by `auto-update` action.
          base: bot/auto-update
          branch: bot/auto-update-pr
          delete-branch: true
