name: clean
on:
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        country: [
            # ad
            # ae,
            # af,
            al
            # am,
            # ao,
            # ar,
            # at,
            # au,
            # aw,
            # az,
            # ba,
            # bb,
            # bd,
            # be,
            # bf,
            # bg,
            # bh,
            # bn,
            # bo,
            # br,
            # bs,
            # by,
            # ca,
            # cd,
            # cg,
            # ch,
            # ci,
            # cl,
            # cm,
            # cn,
            # co,
            # cr,
            # cu,
            # cw,
            # cy,
            # cz,
            # de,
            # dk,
            # do,
            # dz,
            # ec,
            # ee,
            # eg,
            # es,
            # et,
            # fi,
            # fj,
            # fo,
            # fr,
            # ge,
            # gh,
            # gm,
            # gn,
            # gp,
            # gq,
            # gr,
            # gt,
            # hk,
            # hn,
            # hr,
            # ht,
            # hu,
            # id,
            # ie,
            # il,
            # in,
            # iq,
            # ir,
            # is,
            # it,
            # jm,
            # jo,
            # jp,
            # ke,
            # kg,
            # kh,
            # kp,
            # kr,
            # kw,
            # kz,
            # la,
            # lb,
            # li,
            # lk,
            # lt,
            # lu,
            # lv,
            # ly,
            # ma,
            # mc,
            # md,
            # me,
            # mk,
            # ml,
            # mm,
            # mn,
            # mo,
            # mt,
            # mx,
            # my,
            # mz,
            # ne,
            # ng,
            # nl,
            # no,
            # np,
            # nz,
            # om,
            # pa,
            # pe,
            # ph,
            # pk,
            # pl,
            # pr,
            # ps,
            # pt,
            # py,
            # qa,
            # ro,
            # rs,
            # ru,
            # rw,
            # sa,
            # sd,
            # se,
            # sg,
            # si,
            # sk,
            # sl,
            # sm,
            # sn,
            # so,
            # sv,
            # sy,
            # th,
            # tj,
            # tm,
            # tn,
            # tr,
            # tt,
            # tw,
            # tz,
            # ua,
            # ug,
            # uk,
            # us,
            # uy,
            # uz,
            # va,
            # ve,
            # vi,
            # vn,
            # xk,
            # ye,
            # zm,
            # unsorted
          ]
      max-parallel: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Remove Broken Links
        run: node scripts/clean.js --country=${{ matrix.country }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: bot/remove-broken-links
          title: '[Bot] Remove broken links'
          body: |
            This pull request is created automatically.
