name: format

on:
  push:
    branches:
      - master
    paths:
      - 'channels/*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "git checkout master"
      run: git checkout master
      
    - name: "npm install"
      run: npm install
      
    - name: "npm run format"
      run: npm run format
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_SUFFIX: none
