name: Generate Playlists and Deploy

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Generate Playlists and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: .gh-pages
        BUILD_SCRIPT: npm install && npm run generate
