name: Generate grouped playlists

on:
  push:
    branches:
      - master
    paths:
      - 'channels/*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "git checkout master"
      run: git checkout master
      
    - name: "npm install"
      run: npm install

    - name: "npm run generate"
      run: npm run generate
    
    - name: "git add"
      run: git add .
      
    - name: "git config user.name"
      run: git config user.name freearhey
      
    - name: "git config user.email"
      run: git config user.email free.arhey@gmail.com
      
    - name: "git commit -m"
      run: git commit -m "Generated grouped playlists"
    
    - name: "git remote set-url origin"
      run: git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      
    - name: "git branch"
      run: git branch
    
    - name: "git push origin master"
      run: git push origin dev
