name: Generate grouped playlists

on:
  push:
    branches:
      - master
    paths:
      - 'channels/*'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: "npm install"
      run: npm install

    - name: "npm run generate"
      run: npm run generate
